(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-electric-left-right-brace t)
 '(TeX-PDF-mode nil)
 '(TeX-auto-save t)
 '(TeX-master nil)
 '(TeX-parse-self t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(beacon-color "#f2777a")
 '(bibliothek-path (quote ("~/Desktop")) t)
 '(bibtex-completion-bibliography "~/Dropbox/bibliography/references.bib")
 '(bibtex-completion-library-path "~/Dropbox/bibliography/bibtex-pdfs")
 '(bibtex-completion-notes-path "~/Dropbox/bibliography/Notes.org")
 '(bongo-enabled-backends (quote (mplayer)) t)
 '(browse-url-browser-function (quote du-browse-url))
 '(cider-auto-select-error-buffer t t)
 '(cider-repl-history-size 1000 t)
 '(cider-repl-pop-to-buffer-on-connect nil t)
 '(cider-repl-use-clojure-font-lock t t)
 '(cider-repl-wrap-history t t)
 '(cider-show-error-buffer t t)
 '(circe-network-options
   (quote
    (("Freenode" :nick "Solatle" :channels
      ("#org-mode" "#evil-mode" :after-auth "#emacs")
      :nickserv-password du/nickserv-password))) t)
 '(circe-use-cycle-completion t t)
 '(company-idle-delay 0.1)
 '(company-math-allow-latex-symbols-in-faces t)
 '(company-minimum-prefix-length 3)
 '(company-quickhelp-color-background "#4F4F4F")
 '(company-quickhelp-color-foreground "#DCDCCC")
 '(compilation-message-face (quote default))
 '(counsel-find-file-ignore-regexp
   "\\(\\`\\.[^.]\\|\\(?:\\.\\(?:aux\\|b\\(?:bl\\|in\\|lg\\|zr/\\)\\|c\\(?:lass\\|ps?\\)\\|d\\(?:\\(?:64fs\\|fs\\|x\\(?:\\(?:32\\|64\\)fs\\)?\\)l\\)\\|elc\\|f\\(?:asl?\\|mt\\|ns?\\|\\(?:x\\(?:\\(?:32\\|64\\)f\\)\\)?sl\\)\\|g\\(?:it/\\|[lm]o\\)\\|hg/\\|idx\\|kys?\\|l\\(?:bin\\|ib\\|o[ft]\\|x\\(?:\\(?:32\\|64\\)fsl\\)\\|[ano]\\)\\|m\\(?:em\\|o\\)\\|p\\(?:64fsl\\|fsl\\|gs?\\|y[co]\\)\\|s\\(?:o\\|parcf\\|vn/\\|x\\(?:\\(?:32\\|64\\)fsl\\)\\)\\|t\\(?:fm\\|oc\\|ps?\\)\\|ufsl\\|vrs?\\|wx\\(?:\\(?:32\\|64\\)fsl\\)\\|x86f\\|[ao]\\)\\|CVS/\\|_\\(?:\\(?:MTN\\|darcs\\)/\\)\\|~\\)\\'\\)")
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-normal-cursor-color "#657b83")
 '(cua-overwrite-cursor-color "#b58900")
 '(cua-read-only-cursor-color "#859900")
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("3f44e2d33b9deb2da947523e2169031d3707eec0426e78c7b8a646ef773a2077" "628278136f88aa1a151bb2d6c8a86bf2b7631fbea5f0f76cba2a0079cd910f7d" "190a9882bef28d7e944aa610aa68fe1ee34ecea6127239178c7ac848754992df" "9fcac3986e3550baac55dc6175195a4c7537e8aa082043dcbe3f93f548a3a1e0" "a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "1f3113447a652b8436a9938bbac71ecaf022cc73ecd0d76182eb9713aa781f17" "086970da368bb95e42fd4ddac3149e84ce5f165e90dfc6ce6baceae30cf581ef" "3e335d794ed3030fefd0dbd7ff2d3555e29481fe4bbb0106ea11c660d6001767" "0ee3fc6d2e0fc8715ff59aed2432510d98f7e76fe81d183a0eb96789f4d897ca" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "55d31108a7dc4a268a1432cd60a7558824223684afecefa6fae327212c40f8d3" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" default)))
 '(deft-default-extension "org" t)
 '(deft-directory "~/Dropbox/Org" t)
 '(deft-extensions (quote ("org")) t)
 '(deft-text-mode (quote org-mode) t)
 '(dired-dwim-target t)
 '(dired-recursive-copies (quote always))
 '(dired-recursive-deletes (quote always))
 '(ein:jupyter-default-notebook-directory "~/Jupyter/" t)
 '(eir-repl-placement (quote left) t)
 '(emms-info-functions (quote (emms-info-mpd)) t)
 '(emms-player-list (quote (emms-player-mpd)) t)
 '(emms-player-mpd-server-name "localhost" t)
 '(emms-player-mpd-server-port "6610" t)
 '(emms-seek-seconds 5 t)
 '(epa-pinentry-mode (quote loopback))
 '(ess-fancy-comments nil t)
 '(evil-collection-setup-minibuffer t)
 '(evil-cross-lines t)
 '(evil-move-cursor-back nil)
 '(evil-respect-visual-line-mode t)
 '(evil-want-C-u-scroll t)
 '(evil-want-keybinding nil)
 '(eziam-scale-headings t)
 '(fci-rule-color "#eee8d5" t)
 '(flycheck-color-mode-line-face-to-color (quote mode-line-buffer-id))
 '(font-latex-fontify-script nil)
 '(frame-background-mode (quote dark))
 '(geiser-active-implementations (quote (guile chez)) t)
 '(highlight-changes-colors (quote ("#d33682" "#6c71c4")))
 '(highlight-symbol-colors
   (--map
    (solarized-color-blend it "#fdf6e3" 0.25)
    (quote
     ("#b58900" "#2aa198" "#dc322f" "#6c71c4" "#859900" "#cb4b16" "#268bd2"))))
 '(highlight-symbol-foreground-color "#586e75")
 '(highlight-tail-colors
   (quote
    (("#eee8d5" . 0)
     ("#B4C342" . 20)
     ("#69CABF" . 30)
     ("#69B7F0" . 50)
     ("#DEB542" . 60)
     ("#F2804F" . 70)
     ("#F771AC" . 85)
     ("#eee8d5" . 100))))
 '(hl-bg-colors
   (quote
    ("#DEB542" "#F2804F" "#FF6E64" "#F771AC" "#9EA0E5" "#69B7F0" "#69CABF" "#B4C342")))
 '(hl-fg-colors
   (quote
    ("#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3")))
 '(inferior-lisp-program "/usr/local/bin/clisp" t)
 '(ispell-choices-win-default-height 5)
 '(ispell-dictionary "en_US")
 '(ispell-program-name "/usr/local/bin/hunspell")
 '(ivy-dynamic-exhibit-delay-ms 200)
 '(ivy-height 10)
 '(ivy-initial-inputs-alist nil t)
 '(ivy-magic-tilde nil)
 '(ivy-re-builders-alist (quote ((t . ivy--regex-ignore-order))) t)
 '(ivy-use-virtual-buffers t)
 '(ivy-wrap t)
 '(langtool-default-language "en-US" t)
 '(langtool-language-tool-jar
   "/usr/local/Cellar/languagetool/4.1/libexec/languagetool-commandline.jar" t)
 '(magit-diff-use-overlays nil)
 '(magithub-clone-default-directory "~/github" t)
 '(markdown-command "multimarkdown" t)
 '(markdown-enable-math t t)
 '(matlab-indent-function t t)
 '(matlab-mode-install-path "/Applications/MATLAB/MATLAB_R2017b.app/toolbox" t)
 '(matlab-shell-command "/Applications/MATLAB/MATLAB_R2017b.app/bin/matlab" t)
 '(md4rd--oauth-access-token "147565326956-VPG767JAGLr9uxHu6KgzWKoYxeg" t)
 '(md4rd--oauth-refresh-token "147565326956-dDXMWAq0SSME9Qvb6-hafaRsD-s" t)
 '(md4rd-subs-active (quote (emacs Economics writing)) t)
 '(mpc-host "localhost:6610" t)
 '(mu4e-headers-include-related nil)
 '(my-credentials-file "~/.private.el" t)
 '(neo-theme (quote icons))
 '(netease-music-api "YOUR-API-ADDRESS" t)
 '(netease-music-user-id "YOUR-USER-ID" t)
 '(netease-music-user-password "YOUR-PASSWORD" t)
 '(netease-music-username "YOUR-PHONE-NUMBER" t)
 '(nov-text-width 2305843009213693951 t)
 '(nrepl-hide-special-buffers t t)
 '(nrepl-message-colors
   (quote
    ("#dc322f" "#cb4b16" "#b58900" "#546E00" "#B4C342" "#00629D" "#2aa198" "#d33682" "#6c71c4")))
 '(org-bullets-bullet-list (quote ("◉" "○" "●" "◆" "♦")))
 '(org-latex-default-packages-alist
   (quote
    (("AUTO" "inputenc" t
      ("pdflatex"))
     ("T1" "fontenc" t
      ("pdflatex"))
     ("" "graphicx" t nil)
     ("" "grffile" t nil)
     ("" "longtable" nil nil)
     ("" "wrapfig" nil nil)
     ("" "rotating" nil nil)
     ("normalem" "ulem" t nil)
     ("" "amsmath" t nil)
     ("" "textcomp" t nil)
     ("" "amssymb" t nil)
     ("" "capt-of" nil nil)
     ("hidelinks" "hyperref" nil nil))))
 '(org-mime-export-options
   (quote
    (:section-numbers nil :with-author nil :with-toc nil :with-latex imagemagick)) t)
 '(org-mime-up-subtree-heading (quote org-back-to-heading) t)
 '(org-ref-bibliography-notes "~/Dropbox/bibliography/Notes.org")
 '(org-ref-default-bibliography (quote ("~/Dropbox/bibliography/references.bib")))
 '(org-ref-default-citation-link "citet")
 '(org-ref-default-ref-type "eqref")
 '(org-ref-label-color "light green")
 '(org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")
 '(org-ref-ref-color "Brown")
 '(org-ref-show-broken-links nil)
 '(org-startup-truncated nil)
 '(osx-dictionary-use-chinese-text-segmentation t t)
 '(package-selected-packages
   (quote
    (demo-it ein poly-noweb poly-markdown poly-R evil-escape sly rainbow-identifiers org-wc julia-repl smartparens-org web-search julia-mode ess xah-lookup language-detection magithub simple-mpc bongo posframe circe skewer-mode org-beautify-theme evil-collection clj-refactor rainbow-delimiters org-download org-pdfview writeroom-mode org-bullets matlab-mode org org-edna 0blayout pdf-tools ob-ipython smartparens company auto-package-update polymode pandoc-mode auctex)))
 '(pdf-annot-activate-created-annotations t t)
 '(pdf-annot-default-markup-annotation-properties (quote ((color . "#90ee90"))) t)
 '(pdf-view-display-size (quote fit-page))
 '(pdf-view-midnight-colors (quote ("#DCDCCC" . "#383838")))
 '(pdf-view-resize-factor 1.1)
 '(pos-tip-background-color "#eee8d5")
 '(pos-tip-foreground-color "#586e75")
 '(powerline-default-separator (quote butt))
 '(preview-auto-cache-preamble t)
 '(preview-image-type (quote imagemagick))
 '(recentf-auto-cleanup (quote never))
 '(recentf-max-menu-items 15)
 '(recentf-max-saved-items 500)
 '(reftex-plug-into-AUCTeX t)
 '(semantic-matlab-root-directory "/Applications/MATLAB/MATLAB_R2017b.app" t)
 '(send-mail-function (quote smtpmail-send-it))
 '(show-paren-when-point-inside-paren t)
 '(shr-external-rendering-functions (quote ((pre . eww-tag-pre))) t)
 '(shr-width 90)
 '(simple-mpc-playlist-format "%artist%	%album%	%title%	%file%" t)
 '(simple-mpc-table-separator " " t)
 '(truncate-lines nil)
 '(twittering-icon-mode t t)
 '(twittering-use-icon-storage t t)
 '(twittering-use-master-password t t)
 '(vc-annotate-background nil)
 '(vc-annotate-background-mode nil)
 '(vc-annotate-color-map
   (quote
    ((20 . "#dc322f")
     (40 . "#c85d17")
     (60 . "#be730b")
     (80 . "#b58900")
     (100 . "#a58e00")
     (120 . "#9d9100")
     (140 . "#959300")
     (160 . "#8d9600")
     (180 . "#859900")
     (200 . "#669b32")
     (220 . "#579d4c")
     (240 . "#489e65")
     (260 . "#399f7e")
     (280 . "#2aa198")
     (300 . "#2898af")
     (320 . "#2793ba")
     (340 . "#268fc6")
     (360 . "#268bd2"))))
 '(vc-annotate-very-old-color nil)
 '(visual-fill-column-center-text t)
 '(visual-fill-column-width 90)
 '(weechat-color-list
   (quote
    (unspecified "#fdf6e3" "#eee8d5" "#990A1B" "#dc322f" "#546E00" "#859900" "#7B6000" "#b58900" "#00629D" "#268bd2" "#93115C" "#d33682" "#00736F" "#2aa198" "#657b83" "#839496")))
 '(writeroom-bottom-divider-width 0)
 '(writeroom-fullscreen-effect (quote maximized))
 '(writeroom-maximize-window nil)
 '(writeroom-width 90)
 '(xah-lookup-browser-function (quote eww) t)
 '(xterm-color-names
   ["#eee8d5" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#073642"])
 '(xterm-color-names-bright
   ["#fdf6e3" "#cb4b16" "#93a1a1" "#839496" "#657b83" "#6c71c4" "#586e75" "#002b36"]))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(neo-banner-face ((t (:foreground "dark cyan"))))
 '(neo-header-face ((t (:foreground "dark gray" :weight semi-bold))))
 '(vertical-border ((t (:foreground "#3F3F3F"))))
 '(pdf-occur-document-face ((t (:foreground "dark magenta")))))
